src/ActivityBundle/Entity/Activity.php
<?php

namespace ActivityBundle\Entity;

use Symfony\Component\Validator\Constraints\DateTime;
use UserBundle\Entity\User;
use Doctrine\ORM\Mapping as ORM;

/**
 * Class Activity.
 *
 * @author Tom Newby <tom.newby@redeye.co>
 *
 * @ORM\Table(name="activities")
 * @ORM\Entity(repositoryClass="ActivityBundle\Repository\ActivityRepository")
 */
class Activity
{
    const CLASSIFY_COMMUTE_NO = 1;
    const CLASSIFY_COMMUTE_IN = 2;
    const CLASSIFY_COMMUTE_OUT = 3;
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var int
     * @ORM\Column(type="integer", unique=true)
     */
    protected $resourceId;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="UserBundle\Entity\User", inversedBy="activities")
     */
    protected $user;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    protected $name;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $startDate;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $startDateLocal;

    /**
     * @var string
     * @ORM\Column(type="text", nullable=true)
     */
    protected $polyline;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=3, precision=9, nullable=true)
     */
    protected $startLat;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=3, precision=9, nullable=true)
     */
    protected $startLng;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=3, precision=9, nullable=true)
     */
    protected $endLat;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=3, precision=9, nullable=true)
     */
    protected $endLng;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $classifiedAt;

    /**
     * @var int
     * @ORM\Column(type="integer", nullable=true)
     */
    protected $classification;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=3, precision=9, nullable=true)
     */
    protected $value;

    /**
     * @var int
     * @ORM\Column(type="smallint", options={"unsigned"=true}, nullable=true)
     */
    protected $elapsedTime;

    /**
     * @var bool
     * @ORM\Column(type="boolean")
     */
    protected $manual = false;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return int
     */
    public function getResourceId()
    {
        return $this->resourceId;
    }

    /**
     * @param int $resourceId
     *
     * @return $this
     */
    public function setResourceId($resourceId)
    {
        $this->resourceId = $resourceId;

        return $this;
    }

    /**
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * @param User $user
     *
     * @return $this
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->startDate;
    }

    /**
     * @param \DateTime|string $startDate
     *
     * @return $this
     *
     * @throws \Exception
     */
    public function setStartDate($startDate)
    {
        if ($startDate instanceof \DateTime) {
            $this->startDate = $startDate;
        } elseif (is_string($startDate)) {
            // Try converting to a datetime object
            $this->startDate = new \DateTime($startDate);
        } else {
            throw new \Exception(sprintf('Format of %s passed to setStartDate value', gettype($startDate)));
        }

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartDateLocal()
    {
        return $this->startDateLocal;
    }

    /**
     * @param \DateTime|string $startDateLocal
     *
     * @return $this
     *
     * @throws \Exception
     */
    public function setStartDateLocal($startDateLocal)
    {
        if ($startDateLocal instanceof \DateTime) {
            $this->startDateLocal = $startDateLocal;
        } elseif (is_string($startDateLocal)) {
            // Try converting to a datetime object
            $this->startDateLocal = new \DateTime($startDateLocal);
        } else {
            throw new \Exception(sprintf('Format of %s passed to setStartDateLocal value', gettype($startDate)));
        }

        return $this;
    }

    /**
     * @return string
     */
    public function getPolyline()
    {
        return $this->polyline;
    }

    /**
     * @param string $polyline
     *
     * @return $this
     */
    public function setPolyline($polyline)
    {
        $this->polyline = $polyline;

        return $this;
    }

    /**
     * @return float
     */
    public function getStartLat()
    {
        return $this->startLat;
    }

    /**
     * @param float $startLat
     *
     * @return $this
     */
    public function setStartLat($startLat)
    {
        $this->startLat = $startLat;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getStartLng()
    {
        return $this->startLng;
    }

    /**
     * @param mixed $startLng
     *
     * @return $this
     */
    public function setStartLng($startLng)
    {
        $this->startLng = $startLng;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getEndLng()
    {
        return $this->endLng;
    }

    /**
     * @param mixed $endLng
     *
     * @return $this
     */
    public function setEndLng($endLng)
    {
        $this->endLng = $endLng;

        return $this;
    }

    /**
     * @return float
     */
    public function getEndLat()
    {
        return $this->endLat;
    }

    /**
     * @param float $endLat
     *
     * @return $this
     */
    public function setEndLat($endLat)
    {
        $this->endLat = $endLat;

        return $this;
    }

    /**
     * @return int
     */
    public function getClassification()
    {
        return $this->classification;
    }

    /**
     * @param int $classification
     *
     * @return $this
     */
    public function setClassification($classification)
    {
        $this->classification = $classification;

        // No Commute = No Value
        if (self::CLASSIFY_COMMUTE_NO === $classification) {
            $this->setValue(0);
        }

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getClassifiedAt()
    {
        return $this->classifiedAt;
    }

    /**
     * @param \DateTime $classifiedAt
     *
     * @return $this
     */
    public function setClassifiedAt($classifiedAt)
    {
        $this->classifiedAt = $classifiedAt;

        return $this;
    }

    /**
     * @return bool
     */
    public function isClassified()
    {
        return null !== $this->getClassifiedAt();
    }

    public function getClassificationAsString()
    {
        if (!$this->isClassified()) {
            return 'Unclassified';
        }

        $classification = $this->getClassification();

        if (self::CLASSIFY_COMMUTE_IN === $classification) {
            return 'To Work';
        }

        if (self::CLASSIFY_COMMUTE_OUT === $classification) {
            return 'To Home';
        }

        if (self::CLASSIFY_COMMUTE_NO === $classification) {
            return 'N/A';
        }

        return 'Unclassified';
    }

    public static function getClassificationOptions()
    {
        return array(
            'To Work' => self::CLASSIFY_COMMUTE_IN,
            'To Home' => self::CLASSIFY_COMMUTE_OUT,
            'No commute' => self::CLASSIFY_COMMUTE_NO,
        );
    }

    /**
     * @return float
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * @param float $value
     *
     * @return $this
     */
    public function setValue($value)
    {
        $this->value = $value;

        return $this;
    }

    /**
     * @return int
     */
    public function getElapsedTime()
    {
        return $this->elapsedTime;
    }

    /**
     * @param int $elapsedTime
     *
     * @return $this
     */
    public function setElapsedTime($elapsedTime)
    {
        $this->elapsedTime = $elapsedTime;

        return $this;
    }

    public function getEndDate()
    {
        $endDate = clone $this->getStartDate();

        return $endDate->add(\DateInterval::createFromDateString(sprintf('%d seconds', $this->elapsedTime)));
    }

    public function getEndDateLocal()
    {
        $endDateLocal = clone $this->getStartDateLocal();

        return $endDateLocal->add(\DateInterval::createFromDateString(sprintf('%d seconds', $this->elapsedTime)));
    }

    /**
     * @return bool
     */
    public function isCommute()
    {
        $classification = $this->getClassification();

        return $classification === self::CLASSIFY_COMMUTE_IN || $classification === self::CLASSIFY_COMMUTE_OUT;
    }

    /**
     * @return bool
     */
    public function isManual()
    {
        return $this->manual;
    }

    /**
     * @param bool $manual
     *
     * @return $this
     */
    public function setManual($manual)
    {
        $this->manual = $manual;

        return $this;
    }
}

src/ActivityBundle/Controller/ActivityController.php
<?php

namespace ActivityBundle\Controller;

use ActivityBundle\Entity\Activity;
use ActivityBundle\Repository\ActivityRepository;
use ActivityBundle\Services\ActivitySyncService;
use ActivityBundle\Services\BalanceService;
use Mixpanel;
use MixpanelBundle\Mixpanel\Event;
use MixpanelBundle\Services\MixpanelService;
use StravaBundle\Services\ClientFactory;
use Symfony\Bridge\Monolog\Logger;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use UserBundle\Entity\User;

class ActivityController extends Controller
{
    public function listAction(Request $request, $pageId = 1)
    {
        $pageId = intval($pageId);

        if ($pageId < 1) {
            return $this->redirectToRoute('activity.activity.list');
        }

        $user = $this->getUser();

        if (!$user->isSetup()) {
            return $this->redirectToRoute('user.onboard.index');
        }

        /** @var MixpanelService $mixpanel */
        $mixpanel = $this->get('mixpanel');

        $mixpanel->addEvent(new Event('Activity List'));

        /** @var ActivityRepository $activityRepository */
        $activityRepository = $this->get('activity.activity_repository');

        $perPage = 10;

        $activities = $activityRepository->findPaginatedActivitiesForFeed($user, $pageId, $perPage);

        $activityCount = $activityRepository->getActivityCount($user);

        /* @var BalanceService $balance */
        $balanceService = $this->get('activity.balance');

        $balance = $balanceService->getBalanceForUser($user);

        $adIndex = 2; // hard coded for now

        return $this->render('ActivityBundle:Activity:list.html.twig',
            array(
                'user' => $user,
                'activities' => $activities,
                'balance' => $balance,
                'page' => $pageId,
                'total_count' => $activityCount,
                'per_page' => $perPage,
                'show_next' => ($perPage * $pageId) < $activityCount,
                'show_previous' => $pageId > 1,
                'ad_index' => $adIndex
            )
        );
    }

    public function editAction(Request $request, $id)
    {
        /** @var ActivityRepository $activityRepository */
        $activityRepository = $this->get('activity.activity_repository');

        $activity = $activityRepository->findUsersActivityById($this->getUser(), $id);

        if (!$activity instanceof Activity) {
            throw new NotFoundHttpException();
        }

        $form = $this->createFormBuilder($activity)
            //->add('classification')
            ->add('value', MoneyType::class, array(
                'scale' => 2,
                'currency' => $this->getUser()->getCurrency(),
                'constraints' => new GreaterThanOrEqual(array(
                    'value' => 0,
                    'message' => 'Your savings should be a positive number',
                )), ))
            ->add('classification', ChoiceType::class, array(
                'choices' => Activity::getClassificationOptions(),
                'choices_as_values' => true,
            ))
            ->add('submit', SubmitType::class, array('attr' => array('class' => 'btn btn-default')))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $activityRepository->save($activity);

            return $this->redirectToRoute('activity.activity.list');
        }

        return $this->render('ActivityBundle:Activity:edit.html.twig', array('activity' => $activity, 'form' => $form->createView()));
    }

    /**
     * @param int $id
     *
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function refreshAction(int $id)
    {
        /** @var ActivityRepository $activityRepository */
        $activityRepository = $this->get('activity.activity_repository');

        $activity = $activityRepository->find($id);

        if (!$activity instanceof Activity || $activity->getUser() !== $this->getUser()) {
            /** @var Logger $logger */
            $logger = $this->get('logger');

            $logger->addCritical(sprintf('User %s tried to refresh %d', $this->getUser()->getId(), $id));
            throw new NotFoundHttpException();
        }

        /** @var ActivitySyncService $activitySyncService */
        $activitySyncService = $this->get('activity.activity_sync');

        /** @var ClientFactory $clientFactory */
        $clientFactory = $this->get('strava.client_factory');

        /** @var User $user */
        $user = $this->getUser();

        $client = $clientFactory->createClientFromAccessToken($user->getAccessToken());

        $refreshedActivity = $activitySyncService->refreshActivity($activity, $client);

        $this->addFlash('success', sprintf("Refreshed activity '%s'", $refreshedActivity->getName()));

        $this->get('mixpanel')->addEvent(new Event('Refresh Activity', ['Activity Id' => $refreshedActivity->getResourceId()]));

        return $this->redirectToRoute('activity.activity.list');
    }
}

src/ActivityBundle/Resources/views/Activity/_card.html.twig
<div class="strava-card">
    <div class="gopher">
        <span>{{ activity.startDateLocal|date('d M') }}</span>
    </div>
    <img src="http://maps.googleapis.com/maps/api/staticmap?sensor=false&size=400x230&path=weight:3%7Ccolor:red%7Cenc:{{ activity.polyline }}&key={{ google_maps_key }}" alt=""/>
    <div class="title">
        <h3>{{ activity.name }}</h3>
        <a class="refresh-activity" href="{{ path('activity.activity.refresh', { id: activity.id }) }}" title="Refresh Title">
            <span class="icon icon-arrows-ccw"></span>
        </a>
    </div>
        {% if activity.isCommute %}
        <div class="earnings commute">
            <h4>{{ app.user.currency|currency_symbol }}{{ (activity.value|number_format(2)) }}</h4>
        </div>
        {% else %}
        <div class="earnings no-commute">
            <h4>Not a commute</h4>
        </div>
        {% endif %}
    <div class="buttons">
        <a href="https://strava.com/activities/{{ activity.resourceId }}" class="btn btn-smaller btn-orange">View Strava</a>
        <a href="{{ path('activity.activity.edit', { id: activity.id}) }}" class="btn btn-smaller btn-default">Edit</a>
    </div>
</div>

{#{% if activity.isManual %}#}
                {#<div class="activity {{ activity.isCommute ? 'positive' : 'neutral' }}">#}
                    {#{% if activity.isCommute %}#}
                        {#<div class="earnings">#}
                            {#<div class="center">#}
                                {#<h3 class="center-inner">{{ app.user.currency|currency_symbol }}{{ (activity.value|number_format(2)) }}</h3>#}
                            {#</div>#}
                        {#</div>#}
                    {#{% endif %}#}
                    {#<div class="details">#}
                        {#<div class="center">#}
                            {#<div class="center-inner">#}
                                {#<h3>{{ activity.name }}</h3>#}
                                {#<div class="meta">#}
                            {#<span>{{ activity.startDateLocal|date('g:ia') }}</span> |#}
                                    {#<span>{{ activity.classificationAsString }}</span>#}
                                    {#{% if activity.isCommute %}#}
                                        {#| <span>{{ app.user.currency|currency_symbol }}{{ (activity.value|number_format(2)) }}</span>#}
                                    {#{% endif %}#}
                                {#</div>#}
                                {#<div class="actions">#}
                                    {#<a href="https://strava.com/activities/{{ activity.resourceId }}" class="btn btn-smaller btn-orange">View Strava</a>#}
                                    {#<a href="{{ path('activity.activity.edit', { id: activity.id}) }}" class="btn btn-smaller btn-default">Edit</a>#}
                                {#</div>#}
                            {#</div>#}
                        {#</div>#}
                    {#</div>#}
                {#</div>#}
            {#{% else %}#}
                {#<div class="activity {{ activity.isCommute ? 'positive' : 'neutral' }}">#}
                {#<div class="preview">#}
                    {#<img src="http://maps.googleapis.com/maps/api/staticmap?sensor=false&size={{ activity.isCommute ? '400x230' : '400x150' }}&path=weight:3%7Ccolor:red%7Cenc:{{ activity.polyline }}&key={{ google_maps_key }}" alt=""/>#}
                {#</div>#}
                {#{% if activity.isCommute %}#}
                    {#<div class="earnings">#}
                        {#<div class="center">#}
                            {#<h3 class="center-inner">{{ app.user.currency|currency_symbol }}{{ (activity.value|number_format(2)) }}</h3>#}
                        {#</div>#}
                    {#</div>#}
                {#{% endif %}#}
                {#<div class="details">#}
                    {#<div class="center">#}
                        {#<div class="center-inner">#}
                            {#<h3>{{ activity.name }}</h3>#}
                            {#<div class="meta">#}
                            {#<span>{{ activity.startDateLocal|date('g:ia') }} - {{ activity.endDateLocal|date('g:ia') }}#}
                                {#({{ (activity.elapsedTime/(60*60))>=1 ? (activity.elapsedTime/(60*60))|round(0, 'floor') ~ "h" : "" }}{{ ((activity.elapsedTime%(60*60))/60)|round(0, 'floor') }}m)#}
                                {#({{ activity.startDateLocal|date('d M') }})#}
                            {#</span> |#}
                                {#<span>{{ activity.classificationAsString }}</span>#}
                                {#{% if activity.isCommute %}#}
                                    {#| <span>{{ app.user.currency|currency_symbol }}{{(activity.value|number_format(2)) }}</span>#}
                                {#{% endif %}#}
                            {#</div>#}
                            {#<div class="actions">#}
                                {#<a href="https://strava.com/activities/{{ activity.resourceId }}" class="btn btn-smaller btn-orange">View Strava</a>#}
                                {#<a href="{{ path('activity.activity.edit', { id: activity.id}) }}" class="btn btn-smaller btn-default">Edit</a>#}
                            {#</div>#}
                        {#</div>#}
                    {#</div>#}
                {#</div>#}
            {#</div>#}
            {#{% endif %}#}

src/ActivityBundle/Resources/views/Activity/edit.html.twig
{% extends 'app.html.twig' %}

{% block window %}
    <h2>Edit activity</h2>
    <p class="lead">If we managed to accidentally detect this as a commute, you can update it's classification and
            value here.
    </p>
    {{ form_start(form, { attr: { class: 'form-table'}} ) }}
        {{ form_rest(form) }}
    {{ form_end(form) }}

    <a href="{{ path('activity.activity.list') }}" class="btn btn-neutral">Back to Activity List</a>
{% endblock window %}

src/ActivityBundle/Resources/views/Activity/list.html.twig
{% extends 'app.html.twig' %}

{% block window %}
    <h2>Activity List</h2>
    <p class="lead">Here's a list of your activities we've automatically synced and classified from Strava. You can update
    the classifications and amount saved!</p>

    <div class="activity-list-balance mobile-only">
        <div class="icon-group">
            <a href="{{ path('activity.share.share') }}" class="balance" title="Share on Twitter">

                <div class="icon logo">
                    <img src="{{ asset('images/app/images/logo.svg') }}" alt="" class="tiny-logo"/>
                </div>
                <div class="icon balance-number">
                    <h3>
                        {{ render(controller('ActivityBundle:Balance:printBalance')) }}
                    </h3>
                </div>
            </a>
            <div class="tweet">
                <h4>Balance</h4>
                <a class="btn btn-default btn-smaller" href="{{ path('activity.share.share') }}" title="Share"><span class="icon icon-bicycle"></span>Share</a>
            </div>
        </div>
    </div>

    <p class="pagination-header">Showing {{ (page-1)*per_page+1 }} - {{ min((page)*per_page, total_count) }} of {{ total_count }} activities</p>

    <div class="strava-cards">
        {% for activity in activities %}
            {% include 'ActivityBundle:Activity:_card.html.twig' with { activity: activity } %}
        {% endfor %}
    </div>
    
    <div class="pagination">
        {% if show_previous %}
            <a href="{{ path('activity.activity.list', { pageId: page-1 }) }}" class="btn btn-default">Previous Page</a>
        {% endif %}
        {% if show_next %}
            <a href="{{ path('activity.activity.list', { pageId: page+1 }) }}" class="btn btn-default">Next Page</a>
        {% endif %}
    </div>
{% endblock window %}